yatube/about/urls.py
# файл about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [
    #  Главная страница
    path('', views.index, name='index'),
    #  Страница сообществ, slug перед переменной - слова и цифры
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Создание нового поста
    path('create/', views.post_create, name='post_create'),
    # Редактирование поста
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    # Все адреса с префиксом auth/
    # будут перенаправлены в модуль django.contrib.auth
    path('auth/', include('users.urls')),
    # Если какой-то URL не обнаружится в приложении users —
    # Django пойдёт искать его в django.contrib.auth
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.db import models
# Из модуля auth импортируем функцию get_user_model
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):  # наследник класса Model из модуля models
    title = models.CharField(
        max_length=200,
        verbose_name='Название сообщества'
    )
    slug = models.SlugField(
        unique=True,
        max_length=200,
        verbose_name='URL'
    )
    description = models.TextField(
        verbose_name='Описание сообщества'
    )

    def __str__(self) -> str:
        return self.title


class Post(models.Model):  # наследник класса Model из модуля models
    text = models.TextField(verbose_name='Текст')
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name='Автор статьи'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="posts",
        verbose_name='Группа'
    )

    def __str__(self) -> str:
        # выводим текст поста
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        help_texts = {'group': 'Выберите группу', 'text': 'Введите сообщение'}
        fields = ["group", "text"]

yatube/posts/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Post, Group, User
from .forms import PostForm
from .utils import paginate_posts

LAST_POSTS: int = 10


def index(request):
    context = paginate_posts(Post.objects.all(), request, LAST_POSTS)
    return render(request, 'posts/index.html', context)


# Для страницы, на которой будут посты, отфильтрованные по группам;
def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    context = {
        'group': group,
    }
    context.update(paginate_posts(group.posts.all(), request, LAST_POSTS))
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    context = {
        'author': author,
    }
    context.update(paginate_posts(author.posts.all(), request, LAST_POSTS))
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    # Здесь код запроса к модели и создание словаря контекста
    post = get_object_or_404(Post, pk=post_id)
    post_author = post.author.posts.count()
    context = {
        'post': post,
        'post_author': post_author,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', username=post.author)
        return render(request, 'posts/create_post.html', {'form': form})
    form = PostForm()
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        instance=post
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'is_edit': True,
        'post': post,
    }
    return render(request, 'posts/create_post.html', context)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
{% if is_edit %}
  Сохранить запись
{% else %}
  Добавить запись
{% endif %}  
{% endblock %}
{% load user_filters %}
{% block content %} 
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
          {% if is_edit %}
            Сохранить запись
          {% else %}
            Добавить запись
          {% endif %}             
        </div>
        <div class="card-body">
        
        {% if is_edit %}
          <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post.pk %}">
        {% else %}
          <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
        {% endif %}  
          {% csrf_token %}
           
            {% for field in form %}
            <div class="form-group row my-3 p-3 textarea">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>    
              {{ field|addclass:'form-control' }}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}  
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load static %}
  {% block title %}
    {{ group.title }}
  {% endblock %}
  {% block content %}
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
<article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
</article>
    {% if post.group %}    
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>        
    {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
  {% block title %}
    Последние обновления на сайте
  {% endblock %}
  {% block content %}
    <h1>Последние обновления на сайте{{ text }} </h1>
    {% for post in page_obj %}
<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
      <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
</article>
    {% if post.group %}    
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>        
    {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_card.html
  <ul>
    <li>
     Автор: {{ post.author.get_full_name }}
    </li>
    <li>
     Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
  {% block title %}
    Пост {{ post.text|truncatechars:30 }}
  {% endblock %}
  {% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}   
            <li class="list-group-item">
              Группа: {{ page_title }}
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %} 
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post_count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>{{ post.text }}</p>
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}"> 
            Редактировать пост 
          </a>
        </article>
      </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
  {% block title %}
    Профайл пользователя {{ user }}
  {% endblock %}
  {% block content %}
    <h1>Все посты пользователя {{ user }} </h1>
    <h3>Всего постов: {{ post_count }} </h3>   
    {% for post in page_obj %}
<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
      <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
    <p>
      {{ post.text }}
    </p>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
</article>
    {% if post.group %}    
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/update_post.html
{% extends "base.html" %}
{% block title %}{% if not post %} Добавить запись {% else %} Редактировать запись {% endif %}{% endblock %}
{% block content %}
{% load user_filters%}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">{% if not post %} Добавить запись {% else %} Редактировать запись {% endif %}</div>
            <div class="card-body">

                    {% for error in form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endfor %}

                <form method="post" action="{% url 'new_post' %}">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">
                                    {{ field|addclass:"form-control" }}
                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">              
                            <button type="submit" class="btn btn-primary">
                                {% if post %} Сохранить {% else %} Добавить {% endif %}
                            </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}